const fs = require('fs');

// We copy the elements array here to process it.
const elements = [
  { number: 1, symbol: "H", name: "Hydrogen", row: 1, column: 1, category: "Reactive nonmetal" },
  { number: 2, symbol: "He", name: "Helium", row: 1, column: 18, category: "Noble Gas" },
  { number: 3, symbol: "Li", name: "Lithium", row: 2, column: 1, category: "Alkali Metal" },
  { number: 4, symbol: "Be", name: "Beryllium", row: 2, column: 2, category: "Alkaline Earth Metal" },
  { number: 5, symbol: "B", name: "Boron", row: 2, column: 13, category: "Metalloid" },
  { number: 6, symbol: "C", name: "Carbon", row: 2, column: 14, category: "Reactive nonmetal" },
  { number: 7, symbol: "N", name: "Nitrogen", row: 2, column: 15, category: "Reactive nonmetal" },
  { number: 8, symbol: "O", name: "Oxygen", row: 2, column: 16, category: "Reactive nonmetal" },
  { number: 9, symbol: "F", name: "Fluorine", row: 2, column: 17, category: "Halogen" },
  { number: 10, symbol: "Ne", name: "Neon", row: 2, column: 18, category: "Noble Gas" },
  { number: 11, symbol: "Na", name: "Sodium", row: 3, column: 1, category: "Alkali Metal" },
  { number: 12, symbol: "Mg", name: "Magnesium", row: 3, column: 2, category: "Alkaline Earth Metal" },
  { number: 13, symbol: "Al", name: "Aluminum", row: 3, column: 13, category: "Post-transition Metal" },
  { number: 14, symbol: "Si", name: "Silicon", row: 3, column: 14, category: "Metalloid" },
  { number: 15, symbol: "P", name: "Phosphorus", row: 3, column: 15, category: "Reactive nonmetal" },
  { number: 16, symbol: "S", name: "Sulfur", row: 3, column: 16, category: "Reactive nonmetal" },
  { number: 17, symbol: "Cl", name: "Chlorine", row: 3, column: 17, category: "Halogen" },
  { number: 18, symbol: "Ar", name: "Argon", row: 3, column: 18, category: "Noble Gas" },
  { number: 19, symbol: "K", name: "Potassium", row: 4, column: 1, category: "Alkali Metal" },
  { number: 20, symbol: "Ca", name: "Calcium", row: 4, column: 2, category: "Alkaline Earth Metal" },
  { number: 21, symbol: "Sc", name: "Scandium", row: 4, column: 3, category: "Transition Metal" },
  { number: 22, symbol: "Ti", name: "Titanium", row: 4, column: 4, category: "Transition Metal" },
  { number: 23, symbol: "V", name: "Vanadium", row: 4, column: 5, category: "Transition Metal" },
  { number: 24, symbol: "Cr", name: "Chromium", row: 4, column: 6, category: "Transition Metal" },
  { number: 25, symbol: "Mn", name: "Manganese", row: 4, column: 7, category: "Transition Metal" },
  { number: 26, symbol: "Fe", name: "Iron", row: 4, column: 8, category: "Transition Metal" },
  { number: 27, symbol: "Co", name: "Cobalt", row: 4, column: 9, category: "Transition Metal" },
  { number: 28, symbol: "Ni", name: "Nickel", row: 4, column: 10, category: "Transition Metal" },
  { number: 29, symbol: "Cu", name: "Copper", row: 4, column: 11, category: "Transition Metal" },
  { number: 30, symbol: "Zn", name: "Zinc", row: 4, column: 12, category: "Transition Metal" },
  { number: 31, symbol: "Ga", name: "Gallium", row: 4, column: 13, category: "Post-transition Metal" },
  { number: 32, symbol: "Ge", name: "Germanium", row: 4, column: 14, category: "Metalloid" },
  { number: 33, symbol: "As", name: "Arsenic", row: 4, column: 15, category: "Metalloid" },
  { number: 34, symbol: "Se", name: "Selenium", row: 4, column: 16, category: "Reactive nonmetal" },
  { number: 35, symbol: "Br", name: "Bromine", row: 4, column: 17, category: "Halogen" },
  { number: 36, symbol: "Kr", name: "Krypton", row: 4, column: 18, category: "Noble Gas" },
  { number: 37, symbol: "Rb", name: "Rubidium", row: 5, column: 1, category: "Alkali Metal" },
  { number: 38, symbol: "Sr", name: "Strontium", row: 5, column: 2, category: "Alkaline Earth Metal" },
  { number: 39, symbol: "Y", name: "Yttrium", row: 5, column: 3, category: "Transition Metal" },
  { number: 40, symbol: "Zr", name: "Zirconium", row: 5, column: 4, category: "Transition Metal" },
  { number: 41, symbol: "Nb", name: "Niobium", row: 5, column: 5, category: "Transition Metal" },
  { number: 42, symbol: "Mo", name: "Molybdenum", row: 5, column: 6, category: "Transition Metal" },
  { number: 43, symbol: "Tc", name: "Technetium", row: 5, column: 7, category: "Transition Metal" },
  { number: 44, symbol: "Ru", name: "Ruthenium", row: 5, column: 8, category: "Transition Metal" },
  { number: 45, symbol: "Rh", name: "Rhodium", row: 5, column: 9, category: "Transition Metal" },
  { number: 46, symbol: "Pd", name: "Palladium", row: 5, column: 10, category: "Transition Metal" },
  { number: 47, symbol: "Ag", name: "Silver", row: 5, column: 11, category: "Transition Metal" },
  { number: 48, symbol: "Cd", name: "Cadmium", row: 5, column: 12, category: "Transition Metal" },
  { number: 49, symbol: "In", name: "Indium", row: 5, column: 13, category: "Post-transition Metal" },
  { number: 50, symbol: "Sn", name: "Tin", row: 5, column: 14, category: "Post-transition Metal" },
  { number: 51, symbol: "Sb", name: "Antimony", row: 5, column: 15, category: "Metalloid" },
  { number: 52, symbol: "Te", name: "Tellurium", row: 5, column: 16, category: "Metalloid" },
  { number: 53, symbol: "I", name: "Iodine", row: 5, column: 17, category: "Halogen" },
  { number: 54, symbol: "Xe", name: "Xenon", row: 5, column: 18, category: "Noble Gas" },
  { number: 55, symbol: "Cs", name: "Cesium", row: 6, column: 1, category: "Alkali Metal" },
  { number: 56, symbol: "Ba", name: "Barium", row: 6, column: 2, category: "Alkaline Earth Metal" },
  { number: 57, symbol: "La", name: "Lanthanum", row: 6, column: 3, category: "Lanthanide", series: "lanthanide" },
  { number: 72, symbol: "Hf", name: "Hafnium", row: 6, column: 4, category: "Transition Metal" },
  { number: 73, symbol: "Ta", name: "Tantalum", row: 6, column: 5, category: "Transition Metal" },
  { number: 74, symbol: "W", name: "Tungsten", row: 6, column: 6, category: "Transition Metal" },
  { number: 75, symbol: "Re", name: "Rhenium", row: 6, column: 7, category: "Transition Metal" },
  { number: 76, symbol: "Os", name: "Osmium", row: 6, column: 8, category: "Transition Metal" },
  { number: 77, symbol: "Ir", name: "Iridium", row: 6, column: 9, category: "Transition Metal" },
  { number: 78, symbol: "Pt", name: "Platinum", row: 6, column: 10, category: "Transition Metal" },
  { number: 79, symbol: "Au", name: "Gold", row: 6, column: 11, category: "Transition Metal" },
  { number: 80, symbol: "Hg", name: "Mercury", row: 6, column: 12, category: "Transition Metal" },
  { number: 81, symbol: "Tl", name: "Thallium", row: 6, column: 13, category: "Post-transition Metal" },
  { number: 82, symbol: "Pb", name: "Lead", row: 6, column: 14, category: "Post-transition Metal" },
  { number: 83, symbol: "Bi", name: "Bismuth", row: 6, column: 15, category: "Post-transition Metal" },
  { number: 84, symbol: "Po", name: "Polonium", row: 6, column: 16, category: "Post-transition Metal" },
  { number: 85, symbol: "At", name: "Astatine", row: 6, column: 17, category: "Halogen" },
  { number: 86, symbol: "Rn", name: "Radon", row: 6, column: 18, category: "Noble Gas" },
  { number: 87, symbol: "Fr", name: "Francium", row: 7, column: 1, category: "Alkali Metal" },
  { number: 88, symbol: "Ra", name: "Radium", row: 7, column: 2, category: "Alkaline Earth Metal" },
  { number: 89, symbol: "Ac", name: "Actinium", row: 7, column: 3, category: "Actinide", series: "actinide" },
  { number: 104, symbol: "Rf", name: "Rutherfordium", row: 7, column: 4, category: "Transition Metal" },
  { number: 105, symbol: "Db", name: "Dubnium", row: 7, column: 5, category: "Transition Metal" },
  { number: 106, symbol: "Sg", name: "Seaborgium", row: 7, column: 6, category: "Transition Metal" },
  { number: 107, symbol: "Bh", name: "Bohrium", row: 7, column: 7, category: "Transition Metal" },
  { number: 108, symbol: "Hs", name: "Hassium", row: 7, column: 8, category: "Transition Metal" },
  { number: 109, symbol: "Mt", name: "Meitnerium", row: 7, column: 9, category: "Transition Metal" },
  { number: 110, symbol: "Ds", name: "Darmstadtium", row: 7, column: 10, category: "Transition Metal" },
  { number: 111, symbol: "Rg", name: "Roentgenium", row: 7, column: 11, category: "Transition Metal" },
  { number: 112, symbol: "Cn", name: "Copernicium", row: 7, column: 12, category: "Transition Metal" },
  { number: 113, symbol: "Nh", name: "Nihonium", row: 7, column: 13, category: "Post-transition Metal" },
  { number: 114, symbol: "Fl", name: "Flerovium", row: 7, column: 14, category: "Post-transition Metal" },
  { number: 115, symbol: "Mc", name: "Moscovium", row: 7, column: 15, category: "Post-transition Metal" },
  { number: 116, symbol: "Lv", name: "Livermorium", row: 7, column: 16, category: "Post-transition Metal" },
  { number: 117, symbol: "Ts", name: "Tennessine", row: 7, column: 17, category: "Halogen" },
  { number: 118, symbol: "Og", name: "Oganesson", row: 7, column: 18, category: "Noble Gas" },
  { number: 58, symbol: "Ce", name: "Cerium", row: 9, column: 4, category: "Lanthanide", series: "lanthanide" },
  { number: 59, symbol: "Pr", name: "Praseodymium", row: 9, column: 5, category: "Lanthanide", series: "lanthanide" },
  { number: 60, symbol: "Nd", name: "Neodymium", row: 9, column: 6, category: "Lanthanide", series: "lanthanide" },
  { number: 61, symbol: "Pm", name: "Promethium", row: 9, column: 7, category: "Lanthanide", series: "lanthanide" },
  { number: 62, symbol: "Sm", name: "Samarium", row: 9, column: 8, category: "Lanthanide", series: "lanthanide" },
  { number: 63, symbol: "Eu", name: "Europium", row: 9, column: 9, category: "Lanthanide", series: "lanthanide" },
  { number: 64, symbol: "Gd", name: "Gadolinium", row: 9, column: 10, category: "Lanthanide", series: "lanthanide" },
  { number: 65, symbol: "Tb", name: "Terbium", row: 9, column: 11, category: "Lanthanide", series: "lanthanide" },
  { number: 66, symbol: "Dy", name: "Dysprosium", row: 9, column: 12, category: "Lanthanide", series: "lanthanide" },
  { number: 67, symbol: "Ho", name: "Holmium", row: 9, column: 13, category: "Lanthanide", series: "lanthanide" },
  { number: 68, symbol: "Er", name: "Erbium", row: 9, column: 14, category: "Lanthanide", series: "lanthanide" },
  { number: 69, symbol: "Tm", name: "Thulium", row: 9, column: 15, category: "Lanthanide", series: "lanthanide" },
  { number: 70, symbol: "Yb", name: "Ytterbium", row: 9, column: 16, category: "Lanthanide", series: "lanthanide" },
  { number: 71, symbol: "Lu", name: "Lutetium", row: 9, column: 17, category: "Lanthanide", series: "lanthanide" },
  { number: 90, symbol: "Th", name: "Thorium", row: 10, column: 4, category: "Actinide", series: "actinide" },
  { number: 91, symbol: "Pa", name: "Protactinium", row: 10, column: 5, category: "Actinide", series: "actinide" },
  { number: 92, symbol: "U", name: "Uranium", row: 10, column: 6, category: "Actinide", series: "actinide" },
  { number: 93, symbol: "Np", name: "Neptunium", row: 10, column: 7, category: "Actinide", series: "actinide" },
  { number: 94, symbol: "Pu", name: "Plutonium", row: 10, column: 8, category: "Actinide", series: "actinide" },
  { number: 95, symbol: "Am", name: "Americium", row: 10, column: 9, category: "Actinide", series: "actinide" },
  { number: 96, symbol: "Cm", name: "Curium", row: 10, column: 10, category: "Actinide", series: "actinide" },
  { number: 97, symbol: "Bk", name: "Berkelium", row: 10, column: 11, category: "Actinide", series: "actinide" },
  { number: 98, symbol: "Cf", name: "Californium", row: 10, column: 12, category: "Actinide", series: "actinide" },
  { number: 99, symbol: "Es", name: "Einsteinium", row: 10, column: 13, category: "Actinide", series: "actinide" },
  { number: 100, symbol: "Fm", name: "Fermium", row: 10, column: 14, category: "Actinide", series: "actinide" },
  { number: 101, symbol: "Md", name: "Mendelevium", row: 10, column: 15, category: "Actinide", series: "actinide" },
  { number: 102, symbol: "No", name: "Nobelium", row: 10, column: 16, category: "Actinide", series: "actinide" },
  { number: 103, symbol: "Lr", name: "Lawrencium", row: 10, column: 17, category: "Actinide", series: "actinide" }
];

const schemaObject = {};

elements.forEach(el => {
  schemaObject[el.number.toString()] = {
    id: el.number,
    symbol: el.symbol,
    name: el.name,
    level1_basic: {
      type: el.category,
      group: el.column,
      period: el.row.toString(),
      phaseAtSTP: "",
      valenceElectrons: "",
      commonIons: ""
    },
    level2_atomic: {
      mass: {
        highSchool: null,
        universityConventional: null,
        universityInterval: ""
      },
      protons: el.number,
      electronsNeutral: el.number,
      naturalIsotopes: []
    },
    level3_properties: {
      electronic: {
        configuration: "",
        oxidationStates: []
      },
      physical: {
        electronegativity: null,
        firstIonization: "",
        density: "",
        meltingPoint: "",
        boilingPoint: ""
      }
    },
    level4_history_stse: {
      history: {
        discoveryYear: "",
        discoveredBy: "",
        namedBy: ""
      },
      stseContext: [],
      commonUses: [],
      hazards: []
    }
  };
});

fs.writeFileSync('js/data/elementsSkeleton.js', `export const elementsSkeleton = ${JSON.stringify(schemaObject, null, 2)};\n`);
console.log("Successfully created elementsSkeleton.js");
